# Generated by Django 4.1.1 on 2022-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JOBID', models.CharField(max_length=20, unique=True)),
                ('gen_JOBID', models.CharField(blank=True, max_length=20)),
                ('get_id', models.CharField(blank=True, default='', max_length=10)),
                ('client', models.CharField(max_length=255)),
                ('tag_client', models.CharField(blank=True, max_length=5, null=True)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('well', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(default='Iraq', max_length=255)),
                ('BU', models.CharField(blank=True, default='KIU', max_length=3, null=True)),
                ('BL', models.CharField(blank=True, default='SWT', max_length=3, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('isContract', models.BooleanField(blank=True, default=True, null=True)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('h2s', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('co2', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('oilRate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gasRate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['client'],
            },
        ),
    ]
