# Generated by Django 4.1.1 on 2022-10-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobsdb_created_remove_jobsdb_file_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsdb',
            name='tag_client',
        ),
    ]
