# Generated by Django 4.1.1 on 2022-09-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0002_alter_dailyreportdb_bsw_alter_dailyreportdb_orifice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdb',
            name='todayproduced',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='totalproduction',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
