# Generated by Django 4.1.1 on 2022-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0003_alter_dailyreportdb_todayproduced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreportdb',
            name='isCleanup',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='isDST',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='isESP',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='isProduction',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='isSLS',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='dailyreportdb',
            name='isSWT',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
