# Generated by Django 4.1.1 on 2022-09-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0004_dailyreportdb_iscleanup_dailyreportdb_isdst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdb',
            name='bsw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='cmf',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='co2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='flowduration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='h2s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreportdb',
            name='wht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
