# Generated by Django 4.1.1 on 2022-09-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0005_alter_dailyreportdb_bsw_alter_dailyreportdb_cmf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportdb',
            name='supervisorname',
            field=models.CharField(max_length=200),
        ),
    ]
