# Generated by Django 4.1.1 on 2022-09-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipmenMaintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancedb',
            options={'ordering': ['asset']},
        ),
    ]
